config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :countries
  # resources :drinks
  
  namespace :api do
    namespace :v1 do
      get 'drinks/index'
      post 'drinks/create'
      delete 'drinks/:id', to: 'drinks#destroy'
      put 'drinks/:id', to: 'drinks#update'
      get 'drinks/:id', to: 'drinks#show'
      post 'users/create'
      get 'users/:id', to: 'users#show'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "drinks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :countries, class_name: "Country", foreign_key: "id"
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_many :countries, class_name: "Country", foreign_key: "country"
  has_many :styles, class_name: "Style", foreign_key: "style"
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :countries, class_name: "Country", foreign_key: "id"
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  #GET /drinks
  def index
    @countries = Country.all.order(brand: :asc)
    render json: @drinks
  end
  
  #GET /drinks/1
  def show
    if @country
      render json: @country
    else
      render json: @country.errors
    end
  end
  
  #GET /drinks/new
  def new
    @country = Country.new
  end
  #GET /drinks/1/edit
  def edit
  end
  #POST /drinks
  def create
    @country = Country.new(country_params)
    if @country.save
      render json: @country
    else
      render json: @country.errors
    end
  end
  #PATCH/PUT /drinks/1
  def update
  end
  #DELETE /drinks/1
  def destroy
    @country.destroy
    render json: {notice: 'Drink was succesfully removed'}
  end
  private
   def set_country
     @country = Country.find(params[:id])
   end
   def country_params
     params.permit(:brand, :style, :country, :quantity)
   end
end

app/controllers/api/v1/drinks_controller.rb
class Api::V1::DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  #GET /drinks
  def index
    @drinks = Drink.all.order(brand: :asc)
    render json: @drinks
  end
  
  #GET /drinks/1
  def show
    if @drink
      render json: @drink
    else
      render json: @drink.errors
    end
  end
  
  #GET /drinks/new
  def new
    @drink = Drink.new
  end
  #GET /drinks/1/edit
  def edit
  end
  #POST /drinks
  def create
    @drink = Drink.new(drink_params)
    if @drink.save
      render json: @drink
    else
      render json: @drink.errors
    end
  end
  #PATCH/PUT /drinks/1
  def update
  end
  #DELETE /drinks/1
  def destroy
    @drink.destroy
    render json: {notice: 'Drink was succesfully removed'}
  end
  private
   def set_drink
     @drink = Drink.find(params[:id])
   end
   def drink_params
     params.permit(:brand, :style, :country, :quantity, :description)
   end
end

app/controllers/api/v1/styles_controller.rb
class Api::V1::StylesController < ApplicationController
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all.order(name: :asc)
    render json: @users    
  end
  
  def show
    if @user
      render json: @user
    else 
      render json: @user.errors
    end
  end

  def new
    @user = User.new
  end
  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user
    else
      render json: @user.errors
    end
      
  end

  def update
    
  end

  def destroy
    @user.destroy
    render json: {notice: 'User was succesfully removed'}
    
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.permit(:name, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
  
end

app/helpers/api/v1/countries_helper.rb
module Api::V1::CountriesHelper
end

app/helpers/api/v1/drinks_helper.rb
module Api::V1::DrinksHelper
end

app/helpers/api/v1/styles_helper.rb
module Api::V1::StylesHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

  <p>
    <strong>String:</strong>
    <%= country.string %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :string, style: "display: block" %>
    <%= form.text_field :string %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Countries</h1>

<div id="countries">
  <% @countries.each do |country| %>
    <%= render country %>
    <p>
      <%= link_to "Show this country", country %>
    </p>
  <% end %>
</div>

<%= link_to "New country", new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete %>
</div>

app/views/drinks/_drink.html.erb
<div id="<%= dom_id drink %>">
  <p>
    <strong>Brand:</strong>
    <%= drink.brand %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= drink.style %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= drink.country %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= drink.quantity %>
  </p>

</div>

app/views/drinks/_form.html.erb
<%= form_with(model: drink) do |form| %>
  <% if drink.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
        <% drink.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render "form", drink: @drink %>

<br>

<div>
  <%= link_to "Show this drink", @drink %> |
  <%= link_to "Back to drinks", drinks_path %>
</div>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render "form", drink: @drink %>

<br>

<div>
  <%= link_to "Back to drinks", drinks_path %>
</div>

app/views/drinks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @drink %>

<div>
  <%= link_to "Edit this drink", edit_drink_path(@drink) %> |
  <%= link_to "Back to drinks", drinks_path %>

  <%= button_to "Destroy this drink", @drink, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>